In [42]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import os

import warnings

warnings.filterwarnings("ignore", category=FutureWarning)

In [ ]:
df = pd.read_csv('data\\bronze.csv')

C:\Users\andre\AppData\Local\Temp\ipykernel_16392\3236641195.py:1: DtypeWarning: Columns (108) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('dados\\jogadores_fifa_2024_bruto.csv')

In [44]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 50)

In [45]:
df.duplicated().sum()

np.int64(0)

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180021 entries, 0 to 180020
Columns: 109 entries, player_id to gk
dtypes: float64(20), int64(43), object(46)
memory usage: 149.7+ MB

In [47]:
print(df.columns.tolist())

['player_id', 'player_url', 'fifa_version', 'fifa_update', 'update_as_of', 'short_name', 'long_name', 'player_positions', 'overall', 'potential', 'value_eur', 'wage_eur', 'age', 'dob', 'height_cm', 'weight_kg', 'club_team_id', 'club_name', 'league_id', 'league_name', 'league_level', 'club_position', 'club_jersey_number', 'club_loaned_from', 'club_joined_date', 'club_contract_valid_until_year', 'nationality_id', 'nationality_name', 'nation_team_id', 'nation_position', 'nation_jersey_number', 'preferred_foot', 'weak_foot', 'skill_moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause_eur', 'player_tags', 'player_traits', 'pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic', 'attacking_crossing', 'attacking_finishing', 'attacking_heading_accuracy', 'attacking_short_passing', 'attacking_volleys', 'skill_dribbling', 'skill_curve', 'skill_fk_accuracy', 'skill_long_passing', 'skill_ball_control', 'movement_acceleration', 'movement_sprint_speed', 'movement_agility', 'movement_reactions', 'movement_balance', 'power_shot_power', 'power_jumping', 'power_stamina', 'power_strength', 'power_long_shots', 'mentality_aggression', 'mentality_interceptions', 'mentality_positioning', 'mentality_vision', 'mentality_penalties', 'mentality_composure', 'defending_marking_awareness', 'defending_standing_tackle', 'defending_sliding_tackle', 'goalkeeping_diving', 'goalkeeping_handling', 'goalkeeping_kicking', 'goalkeeping_positioning', 'goalkeeping_reflexes', 'goalkeeping_speed', 'ls', 'st', 'rs', 'lw', 'lf', 'cf', 'rf', 'rw', 'lam', 'cam', 'ram', 'lm', 'lcm', 'cm', 'rcm', 'rm', 'lwb', 'ldm', 'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb', 'rcb', 'rb', 'gk']

In [48]:
df['fifa_version'].unique()

array([24., 23., 22., 21., 20., 19., 18., 17., 16., 15.])

In [49]:
df[df['short_name'] == "K. Mbappé"]

,player_id,player_url,fifa_version,fifa_update,update_as_of,short_name,long_name,player_positions,overall,potential,value_eur,wage_eur,age,dob,height_cm,weight_kg,club_team_id,club_name,league_id,league_name,league_level,club_position,club_jersey_number,club_loaned_from,club_joined_date,club_contract_valid_until_year,nationality_id,nationality_name,nation_team_id,nation_position,nation_jersey_number,preferred_foot,weak_foot,skill_moves,international_reputation,work_rate,body_type,real_face,release_clause_eur,player_tags,player_traits,pace,shooting,passing,dribbling,defending,physic,attacking_crossing,attacking_finishing,attacking_heading_accuracy,attacking_short_passing,attacking_volleys,skill_dribbling,skill_curve,skill_fk_accuracy,skill_long_passing,skill_ball_control,movement_acceleration,movement_sprint_speed,movement_agility,movement_reactions,movement_balance,power_shot_power,power_jumping,power_stamina,power_strength,power_long_shots,mentality_aggression,mentality_interceptions,mentality_positioning,mentality_vision,mentality_penalties,mentality_composure,defending_marking_awareness,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes,goalkeeping_speed,ls,st,rs,lw,lf,cf,rf,rw,lam,cam,ram,lm,lcm,cm,rcm,rm,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk
0,231747,/player/231747/kylian-mbappe/240002,24.0,2.0,2023-09-22,K. Mbappé,Kylian Mbappé Lottin,"ST, LW",91,94,181500000.0,230000.0,24,1998-12-20,182,75,73.0,Paris Saint Germain,16.0,Ligue 1,1.0,LW,7.0,NaN,2018-07-01,2024.0,18,France,1335.0,LW,10.0,Right,4,5,5,High/Low,Unique,Yes,349400000.0,"#Speedster, #Dribbler, #Acrobat, #Clinical fin...","Quick Step +, Rapid, Flair, Trivela",97.0,90.0,80.0,92.0,36.0,78.0,78,94,73,86,84,93,80,69,71,92,97,97,93,93,82,90,88,88,77,83,64,38,93,83,84,88.0,26,34,32,13,5,7,11,6,NaN,90+3,90+3,90+3,91,91,91,91,91,89+3,89+3,89+3,89+3,81+3,81+3,81+3,89+3,68+3,63+3,63+3,63+3,68+3,63+3,54+3,54+3,54+3,63+3,18+3
18350,231747,/player/231747/kylian-mbappe/230002,23.0,2.0,2022-09-26,K. Mbappé,Kylian Mbappé Lottin,"ST, LW",91,95,190500000.0,230000.0,23,1998-12-20,182,73,73.0,Paris Saint Germain,16.0,Ligue 1,1.0,ST,7.0,NaN,2018-07-01,2024.0,18,France,1335.0,LS,10.0,Right,4,5,4,High/Low,Unique,Yes,366700000.0,"#Speedster, #Dribbler, #Acrobat, #Clinical Fin...","Solid Player, Flair, Speed Dribbler (AI), Outs...",97.0,89.0,80.0,92.0,36.0,76.0,78,93,72,85,83,93,80,69,71,91,97,97,93,93,81,88,77,87,76,82,64,38,92,83,80,88.0,26,34,32,13,5,7,11,6,NaN,89+3,89+3,89+3,90,90,90,90,90,89+3,89+3,89+3,89+3,81+3,81+3,81+3,89+3,67+3,63+3,63+3,63+3,67+3,63+3,54+3,54+3,54+3,63+3,18+3
36885,231747,https://sofifa.com/player/231747/kylian-mbappe...,22.0,2.0,2021-09-23,K. Mbappé,Kylian Mbappé Lottin,"ST, LW",91,95,194000000.0,230000.0,22,1998-12-20,182,73,73.0,Paris Saint Germain,16.0,Ligue 1,1.0,ST,7.0,NaN,2018-07-01,2022.0,18,France,1335.0,LW,10.0,Right,4,5,4,High/Low,Unique,Yes,373500000.0,"#Speedster, #Dribbler, #Acrobat, #Clinical Fin...","Flair, Speed Dribbler (AI), Outside Foot Shot,...",97.0,88.0,80.0,92.0,36.0,77.0,78,93,72,85,83,93,80,69,71,91,97,97,92,93,83,86,78,88,77,82,62,38,92,82,79,88.0,26,34,32,13,5,7,11,6,NaN,89+3,89+3,89+3,90,90,90,90,90,89+3,89+3,89+3,89+3,81+3,81+3,81+3,89+3,67+3,63+3,63+3,63+3,67+3,63+3,54+3,54+3,54+3,63+3,18+3
56128,231747,https://sofifa.com/player/231747/kylian-mbappe...,21.0,2.0,2020-09-23,K. Mbappé,Kylian Mbappé Lottin,"ST, LW, RW",90,95,185500000.0,160000.0,21,1998-12-20,178,73,73.0,Paris Saint Germain,16.0,Ligue 1,1.0,LS,7.0,NaN,2018-07-01,2022.0,18,France,1335.0,RM,10.0,Right,4,5,3,High/Low,Unique,Yes,203100000.0,"#Speedster, #Dribbler, #Acrobat","Finesse Shot, Flair, Speed Dribbler (AI), Outs...",96.0,86.0,78.0,91.0,39.0,76.0,78,91,73,83,83,92,79,63,70,90,96,96,92,92,82,86,77,86,76,79,62,38,91,80,70,84.0,34,34,32,13,5,7,11,6,NaN,88+3,88+3,88+3,89,89,89,89,89,87+3,87+3,87+3,87+3,79+3,79+3,79+3,87+3,67+3,63+3,63+3,63+3,67+3,63+3,55+3,55+3,55+3,63+3,18+3
75024,231747,https://sofifa.com/player/231747/kylian-mbappe...,20.0,2.0,2019-09-19,K. Mbappé,Kylian Mbappé Lottin,"ST, RW",89,95,93500000.0,150000.0,20,1998-12-20,178,73,73.0,Paris Saint Germain,16.0,Ligue 1,1.0,RW,7.0,NaN,2018-07-01,2022.0,18,France,1335.0,RM,10.0,Right,4,5,3,High/Low,Normal (170-185),Yes,191700000.0,"#Speedster, #Dribbler, #Acrobat","Finesse Shot, Flair, Speed Dribbler (AI), Outs...",96.0,84.0,78.0,90.0,39.0,75.0,78,89,77,82,79,91,79,63,70,90,96,96,92,89,83,83,76,84,76,79,62,38,89,80,70,84.0,34,34,32,13,5,7,11,6,NaN,87+3,87+3,87+3,88,88,88,88,88,86+3,86+3,86+3,87+3,78+3,78+3,78+3,87+3,67+3,62+3,62+3,62+3,67+3,63+3,55+3,55+3,55+3,63+3,17+3
93538,231747,https://sofifa.com/player/231747/kylian-mbappe...,19.0,2.0,2018-08-21,K. Mbappé,Kylian Mbappé Lottin,"RW, ST",87,95,72000000.0,80000.0,19,1998-12-20,178,73,73.0,Paris Saint Germain,16.0,Ligue 1,1.0,RW,7.0,NaN,2018-07-01,2022.0,18,France,1335.0,RM,10.0,Right,4,5,3,High/Medium,Lean (170-185),Yes,147600000.0,"#Speedster, #Dribbler, #Acrobat","Finesse Shot, Flair, Speed Dribbler (AI), Tech...",96.0,81.0,79.0,89.0,39.0,72.0,76,86,77,82,78,89,77,63,73,90,96,96,92,85,83,79,75,83,71,76,62,38,85,84,70,86.0,34,34,32,13,5,7,11,6,NaN,84+2,84+2,84+2,87,86,86,86,87,86+2,86+2,86+2,86+2,78+2,78+2,78+2,86+2,66+2,62+2,62+2,62+2,66+2,62+2,54+2,54+2,54+2,62+2,17+2
111710,231747,https://sofifa.com/player/231747/kylian-mbappe...,18.0,2.0,2017-09-18,K. Mbappé,Kylian Mbappé Lottin,ST,83,94,41500000.0,60000.0,18,1998-12-20,178,73,73.0,Paris Saint Germain,16.0,Ligue 1,1.0,RW,29.0,AS Monaco,NaN,2018.0,18,France,1335.0,CF,12.0,Right,4,4,3,High/Medium,Normal (170-185),Yes,NaN,#Dribbler,"Finesse Shot, Speed Dribbler (AI), Technical D...",90.0,80.0,74.0,85.0,47.0,74.0,70,87,76,78,74,86,75,58,68,87,89,90,78,79,76,79,71,83,74,68,62,49,79,77,70,80.0,41,44,40,13,5,7,11,6,NaN,82+1,82+1,82+1,82,82,82,82,82,81+1,81+1,81+1,81+1,75+1,75+1,75+1,81+1,67+1,64+1,64+1,64+1,67+1,64+1,58+1,58+1,58+1,64+1,16+1
133474,231747,https://sofifa.com/player/231747/kylian-mbappe...,17.0,2.0,2016-09-20,K. Mbappé,Kylian Mbappé Lottin,LW,71,87,3100000.0,20000.0,17,1998-12-20,178,68,69.0,Monaco,16.0,Ligue 1,1.0,SUB,29.0,NaN,2015-12-02,2019.0,18,France,NaN,NaN,NaN,Right,3,3,1,High/Medium,Normal (170-185),No,NaN,NaN,Technical Dribbler (AI),81.0,64.0,65.0,74.0,39.0,62.0,65,67,43,70,57,77,60,55,58,74,82,81,68,59,72,64,58,69,63,57,54,39,66,67,64,67.0,38,40,37,13,5,7,11,6,NaN,66+1,66+1,66+1,71,69,69,69,71,69+1,69+1,69+1,70+1,64+1,64+1,64+1,70+1,58+1,55+1,55+1,55+1,58+1,55+1,48+1,48+1,48+1,55+1,14+1

In [50]:
df = df[df['fifa_version'] == 24.0]

In [51]:
df['fifa_update'].unique()

array([2.])

In [ ]:
columns_to_drop = ['player_url', 'fifa_version', 'fifa_update', 'update_as_of', 'dob', 'height_cm', 'weight_kg',
                        'club_team_id', 'league_id', 'league_level', 'club_position', 'club_jersey_number',
                        'club_loaned_from', 'club_joined_date', 'nationality_id',
                        'nation_team_id', 'nation_position', 'nation_jersey_number', 'preferred_foot', 'weak_foot', 'skill_moves',
                        'international_reputation', 'body_type', 'real_face', 'ls', 'st', 'rs', 'lw', 'lf', 'cf', 'rf', 'rw', 'lam', 'cam', 'ram', 'lm', 'lcm', 'cm', 'rcm', 'rm', 'lwb',
                        'ldm', 'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb', 'rcb', 'rb', 'gk']



df_caracteristics = df.drop(columns=columns_to_drop, axis =1)

In [ ]:
df_caracteristics.duplicated().sum()

np.int64(0)

In [ ]:
df_caracteristics

,player_id,short_name,long_name,player_positions,overall,potential,value_eur,wage_eur,age,club_name,league_name,club_contract_valid_until_year,nationality_name,work_rate,release_clause_eur,player_tags,player_traits,pace,shooting,passing,dribbling,defending,physic,attacking_crossing,attacking_finishing,attacking_heading_accuracy,attacking_short_passing,attacking_volleys,skill_dribbling,skill_curve,skill_fk_accuracy,skill_long_passing,skill_ball_control,movement_acceleration,movement_sprint_speed,movement_agility,movement_reactions,movement_balance,power_shot_power,power_jumping,power_stamina,power_strength,power_long_shots,mentality_aggression,mentality_interceptions,mentality_positioning,mentality_vision,mentality_penalties,mentality_composure,defending_marking_awareness,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes,goalkeeping_speed
0,231747,K. Mbappé,Kylian Mbappé Lottin,"ST, LW",91,94,181500000.0,230000.0,24,Paris Saint Germain,Ligue 1,2024.0,France,High/Low,349400000.0,"#Speedster, #Dribbler, #Acrobat, #Clinical fin...","Quick Step +, Rapid, Flair, Trivela",97.0,90.0,80.0,92.0,36.0,78.0,78,94,73,86,84,93,80,69,71,92,97,97,93,93,82,90,88,88,77,83,64,38,93,83,84,88.0,26,34,32,13,5,7,11,6,NaN
1,239085,E. Haaland,Erling Braut Haaland,ST,91,94,185000000.0,340000.0,22,Manchester City,Premier League,2027.0,Norway,High/Medium,356100000.0,"#Aerial threat, #Distance shooter, #Strength, ...","Acrobatic +, Power Header, Quick Step",89.0,93.0,66.0,80.0,45.0,88.0,47,96,83,77,90,79,77,62,53,82,82,94,76,94,72,94,93,76,93,86,87,43,96,74,84,87.0,38,47,29,7,14,13,11,7,NaN
2,192985,K. De Bruyne,Kevin De Bruyne,"CM, CAM",91,91,103000000.0,350000.0,32,Manchester City,Premier League,2025.0,Belgium,High/Medium,190600000.0,"#Dribbler, #Playmaker, #Distance shooter, #Cro...","Pinged Pass +, Dead Ball, Incisive Pass, Long ...",72.0,88.0,94.0,87.0,65.0,78.0,95,85,55,94,83,86,92,83,94,92,72,72,74,92,78,92,72,88,74,92,75,66,88,95,83,88.0,66,70,53,15,13,5,10,13,NaN
3,158023,L. Messi,Lionel Andrés Messi Cuccittini,"CF, CAM",90,90,41000000.0,23000.0,36,Inter Miami,Major League Soccer,2025.0,Argentina,Low/Low,61500000.0,"#Dribbler, #Playmaker, #FK Specialist, #Acroba...","Technical +, Finesse Shot, Dead Ball, Pinged P...",80.0,87.0,90.0,94.0,33.0,64.0,83,89,60,91,86,96,93,93,90,93,87,74,91,88,95,83,71,70,68,90,44,40,91,92,75,96.0,20,35,24,6,11,15,14,8,NaN
4,165153,K. Benzema,Karim Benzema,"CF, ST",90,90,51000000.0,95000.0,35,Al Ittihad,Pro League,2026.0,France,Medium/Medium,81600000.0,"#Poacher, #Aerial threat, #Clinical finisher, ...","Finesse Shot +, Dead Ball, Pinged Pass, Tiki T...",79.0,88.0,83.0,87.0,39.0,78.0,75,91,90,89,88,87,82,73,76,91,78,79,77,92,72,87,85,82,82,81,63,39,92,90,85,90.0,43,24,18,13,11,5,5,7,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18345,273759,S. Telem,Saphaba Singh Telem,CB,47,57,100000.0,500.0,20,Jamshedpur,Super League,2024.0,India,Medium/Medium,155000.0,NaN,NaN,60.0,25.0,25.0,28.0,47.0,61.0,23,20,42,27,27,20,23,26,20,25,63,57,43,40,70,39,62,56,68,20,47,45,20,28,34,39.0,51,46,47,15,7,14,6,8,NaN
18346,269013,Jin Liangkuan,金良宽,CB,47,55,100000.0,1000.0,21,Meizhou Hakka,Super League,2028.0,China PR,Medium/Medium,175000.0,NaN,NaN,55.0,28.0,31.0,33.0,51.0,47.0,26,25,45,32,30,26,32,26,25,31,56,55,46,45,59,36,36,56,44,23,46,50,28,38,38,46.0,53,52,48,8,13,9,6,7,NaN
18347,272748,M. Mewlan,买乌郎·米吉提,ST,47,55,100000.0,2000.0,19,Shandong Taishan,Super League,2024.0,China PR,Medium/Low,175000.0,NaN,NaN,68.0,46.0,38.0,46.0,16.0,45.0,32,49,41,44,37,42,31,34,31,44,70,66,57,49,69,44,40,54,46,41,34,12,43,42,61,40.0,11,13,19,12,6,7,10,8,NaN
18348,269534,Yin Jie,尹杰,CM,47,54,90000.0,1000.0,21,Zhejiang,Super League,2023.0,China PR,Medium/Medium,158000.0,NaN,NaN,57.0,37.0,46.0,46.0,38.0,57.0,36,32,42,54,36,43,34,35,50,45,59,56,60,44,67,44,48,59,60,35,50,36,53,46,40,39.0,35,38,45,7,7,13,12,14,NaN
18349,269541,Wu Yuhang,吴宇航,CDM,47,53,70000.0,1000.0,22,Zhejiang,Super League,2023.0,China PR,Medium/Medium,123000.0,NaN,NaN,56.0,34.0,43.0,45.0,43.0,51.0,35,31,42,51,26,43,32,34,50,42,51,60,57,45,60,40,38,49,51,32,56,43,37,35,41,39.0,40,45,51,11,12,5,13,8,NaN

In [ ]:
df_caracteristics.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18350 entries, 0 to 18349
Data columns (total 58 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   player_id                       18350 non-null  int64
 1   short_name                      18350 non-null  object
 2   long_name                       18350 non-null  object
 3   player_positions                18350 non-null  object
 4   overall                         18350 non-null  int64
 5   potential                       18350 non-null  int64
 6   value_eur                       18250 non-null  float64
 7   wage_eur                        18263 non-null  float64
 8   age                             18350 non-null  int64
 9   club_name                       18263 non-null  object
 10  league_name                     18263 non-null  object
 11  club_contract_valid_until_year  18263 non-null  float64
 12  nationality_name                18350 non-null  object
 13  work_rate                       18350 non-null  object
 14  release_clause_eur              17070 non-null  float64
 15  player_tags                     1252 non-null   object
 16  player_traits                   8609 non-null   object
 17  pace                            16305 non-null  float64
 18  shooting                        16305 non-null  float64
 19  passing                         16305 non-null  float64
 20  dribbling                       16305 non-null  float64
 21  defending                       16305 non-null  float64
 22  physic                          16305 non-null  float64
 23  attacking_crossing              18350 non-null  int64
 24  attacking_finishing             18350 non-null  int64
 25  attacking_heading_accuracy      18350 non-null  int64
 26  attacking_short_passing         18350 non-null  int64
 27  attacking_volleys               18350 non-null  int64
 28  skill_dribbling                 18350 non-null  int64
 29  skill_curve                     18350 non-null  int64
 30  skill_fk_accuracy               18350 non-null  int64
 31  skill_long_passing              18350 non-null  int64
 32  skill_ball_control              18350 non-null  int64
 33  movement_acceleration           18350 non-null  int64
 34  movement_sprint_speed           18350 non-null  int64
 35  movement_agility                18350 non-null  int64
 36  movement_reactions              18350 non-null  int64
 37  movement_balance                18350 non-null  int64
 38  power_shot_power                18350 non-null  int64
 39  power_jumping                   18350 non-null  int64
 40  power_stamina                   18350 non-null  int64
 41  power_strength                  18350 non-null  int64
 42  power_long_shots                18350 non-null  int64
 43  mentality_aggression            18350 non-null  int64
 44  mentality_interceptions         18350 non-null  int64
 45  mentality_positioning           18350 non-null  int64
 46  mentality_vision                18350 non-null  int64
 47  mentality_penalties             18350 non-null  int64
 48  mentality_composure             18350 non-null  float64
 49  defending_marking_awareness     18350 non-null  int64
 50  defending_standing_tackle       18350 non-null  int64
 51  defending_sliding_tackle        18350 non-null  int64
 52  goalkeeping_diving              18350 non-null  int64
 53  goalkeeping_handling            18350 non-null  int64
 54  goalkeeping_kicking             18350 non-null  int64
 55  goalkeeping_positioning         18350 non-null  int64
 56  goalkeeping_reflexes            18350 non-null  int64
 57  goalkeeping_speed               2045 non-null   float64
dtypes: float64(12), int64(37), object(9)
memory usage: 8.3+ MB

In [ ]:
df_caracteristics.isna().sum()

player_id                      0
short_name                     0
long_name                      0
player_positions               0
overall                        0
                           ...
goalkeeping_handling           0
goalkeeping_kicking            0
goalkeeping_positioning        0
goalkeeping_reflexes           0
goalkeeping_speed          16305
Length: 58, dtype: int64

In [ ]:
columns_to_filter = ['pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic']
df_nan = df_caracteristics[df_caracteristics[columns_to_filter].isna().any(axis=1)]
df_nan['player_positions'].unique()
# Making sure that all NaN values are from goalkeepers

In [ ]:
list_nan_gs = df_caracteristics[df_caracteristics['goalkeeping_speed'].isna()]['player_positions'].unique()

"GK" in list_nan_gs

# Makign sure there were no goalkeepers with NaN on goalkeeping_speed

False

In [ ]:
df_caracteristics = df_caracteristics.fillna(0)

df_caracteristics.isna().sum()

player_id                  0
short_name                 0
long_name                  0
player_positions           0
overall                    0
                          ..
goalkeeping_handling       0
goalkeeping_kicking        0
goalkeeping_positioning    0
goalkeeping_reflexes       0
goalkeeping_speed          0
Length: 58, dtype: int64

In [ ]:
df_caracteristics['work_rate'].unique()

array(['High/Low', 'High/Medium', 'Low/Low', 'Medium/Medium', 'High/High',
       'Medium/High', 'Medium/Low', 'Low/High', 'Low/Medium'],
      dtype=object)

In [ ]:
df_caracteristics[['attacking_work_rate', 'defending_work_rate']] = df_caracteristics['work_rate'].str.split('/', expand=True)
df_caracteristics.drop(columns='work_rate', axis=1, inplace=True)
df_caracteristics.head()

,player_id,short_name,long_name,player_positions,overall,potential,value_eur,wage_eur,age,club_name,league_name,club_contract_valid_until_year,nationality_name,release_clause_eur,player_tags,player_traits,pace,shooting,passing,dribbling,defending,physic,attacking_crossing,attacking_finishing,attacking_heading_accuracy,attacking_short_passing,attacking_volleys,skill_dribbling,skill_curve,skill_fk_accuracy,skill_long_passing,skill_ball_control,movement_acceleration,movement_sprint_speed,movement_agility,movement_reactions,movement_balance,power_shot_power,power_jumping,power_stamina,power_strength,power_long_shots,mentality_aggression,mentality_interceptions,mentality_positioning,mentality_vision,mentality_penalties,mentality_composure,defending_marking_awareness,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes,goalkeeping_speed,attacking_work_rate,defending_work_rate
0,231747,K. Mbappé,Kylian Mbappé Lottin,"ST, LW",91,94,181500000.0,230000.0,24,Paris Saint Germain,Ligue 1,2024.0,France,349400000.0,"#Speedster, #Dribbler, #Acrobat, #Clinical fin...","Quick Step +, Rapid, Flair, Trivela",97.0,90.0,80.0,92.0,36.0,78.0,78,94,73,86,84,93,80,69,71,92,97,97,93,93,82,90,88,88,77,83,64,38,93,83,84,88.0,26,34,32,13,5,7,11,6,0.0,High,Low
1,239085,E. Haaland,Erling Braut Haaland,ST,91,94,185000000.0,340000.0,22,Manchester City,Premier League,2027.0,Norway,356100000.0,"#Aerial threat, #Distance shooter, #Strength, ...","Acrobatic +, Power Header, Quick Step",89.0,93.0,66.0,80.0,45.0,88.0,47,96,83,77,90,79,77,62,53,82,82,94,76,94,72,94,93,76,93,86,87,43,96,74,84,87.0,38,47,29,7,14,13,11,7,0.0,High,Medium
2,192985,K. De Bruyne,Kevin De Bruyne,"CM, CAM",91,91,103000000.0,350000.0,32,Manchester City,Premier League,2025.0,Belgium,190600000.0,"#Dribbler, #Playmaker, #Distance shooter, #Cro...","Pinged Pass +, Dead Ball, Incisive Pass, Long ...",72.0,88.0,94.0,87.0,65.0,78.0,95,85,55,94,83,86,92,83,94,92,72,72,74,92,78,92,72,88,74,92,75,66,88,95,83,88.0,66,70,53,15,13,5,10,13,0.0,High,Medium
3,158023,L. Messi,Lionel Andrés Messi Cuccittini,"CF, CAM",90,90,41000000.0,23000.0,36,Inter Miami,Major League Soccer,2025.0,Argentina,61500000.0,"#Dribbler, #Playmaker, #FK Specialist, #Acroba...","Technical +, Finesse Shot, Dead Ball, Pinged P...",80.0,87.0,90.0,94.0,33.0,64.0,83,89,60,91,86,96,93,93,90,93,87,74,91,88,95,83,71,70,68,90,44,40,91,92,75,96.0,20,35,24,6,11,15,14,8,0.0,Low,Low
4,165153,K. Benzema,Karim Benzema,"CF, ST",90,90,51000000.0,95000.0,35,Al Ittihad,Pro League,2026.0,France,81600000.0,"#Poacher, #Aerial threat, #Clinical finisher, ...","Finesse Shot +, Dead Ball, Pinged Pass, Tiki T...",79.0,88.0,83.0,87.0,39.0,78.0,75,91,90,89,88,87,82,73,76,91,78,79,77,92,72,87,85,82,82,81,63,39,92,90,85,90.0,43,24,18,13,11,5,5,7,0.0,Medium,Medium

In [ ]:
# Para manter na escala de 0 - 100, vamos atribuir valores numéricos à essas duas colunas que podem ser traduzidas como 
# Comprometimetno no ataque e Comprometimento na defesa. Já que não há diferenciação baseado no overall, 33 será baixo comprometimento, 66 médio e 99 alto

df_caracteristics['attacking_work_rate'] = df_caracteristics['attacking_work_rate'].apply(lambda x: 33 if x == 'Low' else (66 if x == 'Medium' else 99))


df_caracteristics['defending_work_rate'] = df_caracteristics['defending_work_rate'].apply(lambda x: 33 if x == 'Low' else (66 if x == 'Medium' else 99))

In [ ]:
df_caracteristics.head()

,player_id,short_name,long_name,player_positions,overall,potential,value_eur,wage_eur,age,club_name,league_name,club_contract_valid_until_year,nationality_name,release_clause_eur,player_tags,player_traits,pace,shooting,passing,dribbling,defending,physic,attacking_crossing,attacking_finishing,attacking_heading_accuracy,attacking_short_passing,attacking_volleys,skill_dribbling,skill_curve,skill_fk_accuracy,skill_long_passing,skill_ball_control,movement_acceleration,movement_sprint_speed,movement_agility,movement_reactions,movement_balance,power_shot_power,power_jumping,power_stamina,power_strength,power_long_shots,mentality_aggression,mentality_interceptions,mentality_positioning,mentality_vision,mentality_penalties,mentality_composure,defending_marking_awareness,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes,goalkeeping_speed,attacking_work_rate,defending_work_rate
0,231747,K. Mbappé,Kylian Mbappé Lottin,"ST, LW",91,94,181500000.0,230000.0,24,Paris Saint Germain,Ligue 1,2024.0,France,349400000.0,"#Speedster, #Dribbler, #Acrobat, #Clinical fin...","Quick Step +, Rapid, Flair, Trivela",97.0,90.0,80.0,92.0,36.0,78.0,78,94,73,86,84,93,80,69,71,92,97,97,93,93,82,90,88,88,77,83,64,38,93,83,84,88.0,26,34,32,13,5,7,11,6,0.0,99,33
1,239085,E. Haaland,Erling Braut Haaland,ST,91,94,185000000.0,340000.0,22,Manchester City,Premier League,2027.0,Norway,356100000.0,"#Aerial threat, #Distance shooter, #Strength, ...","Acrobatic +, Power Header, Quick Step",89.0,93.0,66.0,80.0,45.0,88.0,47,96,83,77,90,79,77,62,53,82,82,94,76,94,72,94,93,76,93,86,87,43,96,74,84,87.0,38,47,29,7,14,13,11,7,0.0,99,66
2,192985,K. De Bruyne,Kevin De Bruyne,"CM, CAM",91,91,103000000.0,350000.0,32,Manchester City,Premier League,2025.0,Belgium,190600000.0,"#Dribbler, #Playmaker, #Distance shooter, #Cro...","Pinged Pass +, Dead Ball, Incisive Pass, Long ...",72.0,88.0,94.0,87.0,65.0,78.0,95,85,55,94,83,86,92,83,94,92,72,72,74,92,78,92,72,88,74,92,75,66,88,95,83,88.0,66,70,53,15,13,5,10,13,0.0,99,66
3,158023,L. Messi,Lionel Andrés Messi Cuccittini,"CF, CAM",90,90,41000000.0,23000.0,36,Inter Miami,Major League Soccer,2025.0,Argentina,61500000.0,"#Dribbler, #Playmaker, #FK Specialist, #Acroba...","Technical +, Finesse Shot, Dead Ball, Pinged P...",80.0,87.0,90.0,94.0,33.0,64.0,83,89,60,91,86,96,93,93,90,93,87,74,91,88,95,83,71,70,68,90,44,40,91,92,75,96.0,20,35,24,6,11,15,14,8,0.0,33,33
4,165153,K. Benzema,Karim Benzema,"CF, ST",90,90,51000000.0,95000.0,35,Al Ittihad,Pro League,2026.0,France,81600000.0,"#Poacher, #Aerial threat, #Clinical finisher, ...","Finesse Shot +, Dead Ball, Pinged Pass, Tiki T...",79.0,88.0,83.0,87.0,39.0,78.0,75,91,90,89,88,87,82,73,76,91,78,79,77,92,72,87,85,82,82,81,63,39,92,90,85,90.0,43,24,18,13,11,5,5,7,0.0,66,66

In [ ]:
file_path = 'data\\silver.csv'

# 
data_folder = os.path.dirname(file_path)
if not os.path.exists(data_folder):
    os.makedirs(data_folder)
    print(f"Pasta criada: {data_folder}")

# Salva o DataFrame no arquivo CSV
df_caracteristics.to_csv(file_path, index=False)

print(f"Arquivo salvo: {file_path}")

Arquivo salvo: dados\jogadores_fifa_2024_limpo.csv

In [ ]:
df_caracteristics

,player_id,short_name,long_name,player_positions,overall,pace,shooting,passing,dribbling,defending,physic,attacking_crossing,attacking_finishing,attacking_heading_accuracy,attacking_short_passing,attacking_volleys,skill_dribbling,skill_curve,skill_fk_accuracy,skill_long_passing,skill_ball_control,movement_acceleration,movement_sprint_speed,movement_agility,movement_reactions,movement_balance,power_shot_power,power_jumping,power_stamina,power_strength,power_long_shots,mentality_aggression,mentality_interceptions,mentality_positioning,mentality_vision,mentality_penalties,mentality_composure,defending_marking_awareness,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes,goalkeeping_speed,attacking_work_rate,defending_work_rate
0,231747,K. Mbappé,Kylian Mbappé Lottin,"Atacante, Extremo",91,97.0,90.0,80.0,92.0,36.0,78.0,78,94,73,86,84,93,80,69,71,92,97,97,93,93,82,90,88,88,77,83,64,38,93,83,84,88.0,26,34,32,13,5,7,11,6,0.0,99,33
1,239085,E. Haaland,Erling Braut Haaland,Atacante,91,89.0,93.0,66.0,80.0,45.0,88.0,47,96,83,77,90,79,77,62,53,82,82,94,76,94,72,94,93,76,93,86,87,43,96,74,84,87.0,38,47,29,7,14,13,11,7,0.0,99,66
2,192985,K. De Bruyne,Kevin De Bruyne,Meio campo,91,72.0,88.0,94.0,87.0,65.0,78.0,95,85,55,94,83,86,92,83,94,92,72,72,74,92,78,92,72,88,74,92,75,66,88,95,83,88.0,66,70,53,15,13,5,10,13,0.0,99,66
3,158023,L. Messi,Lionel Andrés Messi Cuccittini,"Atacante, Meio campo",90,80.0,87.0,90.0,94.0,33.0,64.0,83,89,60,91,86,96,93,93,90,93,87,74,91,88,95,83,71,70,68,90,44,40,91,92,75,96.0,20,35,24,6,11,15,14,8,0.0,33,33
4,165153,K. Benzema,Karim Benzema,Atacante,90,79.0,88.0,83.0,87.0,39.0,78.0,75,91,90,89,88,87,82,73,76,91,78,79,77,92,72,87,85,82,82,81,63,39,92,90,85,90.0,43,24,18,13,11,5,5,7,0.0,66,66
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18345,273759,S. Telem,Saphaba Singh Telem,Zagueiro,47,60.0,25.0,25.0,28.0,47.0,61.0,23,20,42,27,27,20,23,26,20,25,63,57,43,40,70,39,62,56,68,20,47,45,20,28,34,39.0,51,46,47,15,7,14,6,8,0.0,66,66
18346,269013,Jin Liangkuan,金良宽,Zagueiro,47,55.0,28.0,31.0,33.0,51.0,47.0,26,25,45,32,30,26,32,26,25,31,56,55,46,45,59,36,36,56,44,23,46,50,28,38,38,46.0,53,52,48,8,13,9,6,7,0.0,66,66
18347,272748,M. Mewlan,买乌郎·米吉提,Atacante,47,68.0,46.0,38.0,46.0,16.0,45.0,32,49,41,44,37,42,31,34,31,44,70,66,57,49,69,44,40,54,46,41,34,12,43,42,61,40.0,11,13,19,12,6,7,10,8,0.0,66,33
18348,269534,Yin Jie,尹杰,Meio campo,47,57.0,37.0,46.0,46.0,38.0,57.0,36,32,42,54,36,43,34,35,50,45,59,56,60,44,67,44,48,59,60,35,50,36,53,46,40,39.0,35,38,45,7,7,13,12,14,0.0,66,66
18349,269541,Wu Yuhang,吴宇航,Volante,47,56.0,34.0,43.0,45.0,43.0,51.0,35,31,42,51,26,43,32,34,50,42,51,60,57,45,60,40,38,49,51,32,56,43,37,35,41,39.0,40,45,51,11,12,5,13,8,0.0,66,66